### ISSUE TITLE
Cannot retrieve the payload with request.payload in onResponse and mapUri

### ISSUE THREAD

**Issue by a-wf** [hapijs/h2o2#130]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v16.6.2
* *module version*: 9.1.0
* *environment* (e.g. node, browser, native): node, typescript
* *used with* (e.g. hapi application, another framework, standalone, ...): a hapi application
* *any other relevant information*:

#### What problem are you trying to solve?
I try to retrieve and parse the payload in mapUri and onResponse, but the request.payload is other things instead of my request's payload

#### Do you have a new or modified API suggestion to solve the problem?

**Comment by joshkel** [comment]
Try setting your route's options.payload to `{ output: 'data', parse: false }`. For example:

```js
server.route({
  path: myProxyPath,
  handler: {
    proxy: {
      mapUri: myMapUri
    },
    options: {
      payload: {
        output: 'data',
        parse: false
      }
    }
  }
});
```

h2o2-enabled routes change the default [route.options.payload.output](https://hapi.dev/api/?v=21.3.2#-routeoptionspayloadoutput) to `'stream'`. This can save resources and speed up the request (Hapi can stream the payload to the proxied target instead of waiting until it fully buffers it in memory), but it interferes with retrieving and parsing the payload yourself.
