### ISSUE TITLE
Allow payload to be parsed when proxying

### ISSUE THREAD

**Issue by cur3n4** [hapijs/h2o2#22]
I am building a microservices api gateway which basically proxies the requests to different services. 

I would like to be able to validate the request payload before proxying. This is mainly because the api gateway might accept a subset of the service payload (for example a public api gateway will allow only to submit just a few fields for a certain service, and no the whole payload).

Currently in order to validate the payload, it is required to set the payload parse to true. However the proxy prevents parsing the payload.

Related to https://github.com/hapijs/hapi/issues/2260

**Comment by hueniverse** [comment]
This was requested many times and the answer is that you can simply fork this and make the changes you want. Parsing the payload defeats the purpose of this code because it requires loading everything into memory first. If you take the features you want and write your own, it will be simpler and more effective.

**Comment by cur3n4** [comment]
Understood. 
However, one could argue that this request is quite close to the example in the README using onResponse and loading the whole response into memory.
Thanks for the answer anyway.

**Comment by antony** [comment]
Without raising another issue, whilst I agree that having this as default behaviour defeats the purpose, it would be a really good feature to have here, since something I'm using this module a lot for (and it is perfect for it), is proxying APIs for integration tests, whereby you don't want to rewrite the entire API and have to maintain that, but simply augment the real thing with some adjusted data - with the responses being based on certain values entered during testing (which would come through in the JSON payload).

Forking it and making this frequently requested change means that I'd have to maintain my own version of the module, which isn't ideal, or further pollute NPM with a very same-y module (and then there would be N others who do the same).

So I understand the thinking, but I think the ability to explicitly allow parsing where needed (and take the memory/speed hit in this instance) could be a pretty suitable feature for this module, and it expands the use cases of it considerably.
